version: '3'

services:
  libraryproject:
    restart: "on-failure"
    build: 
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    ports:
      - 8001:8001
    volumes:
      - ./libraryproject:/libraryproject
    depends_on:
      - db
  db:
    restart: always
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: Bibliothèque
      POSTGRES_USER: library
      POSTGRES_PASSWORD: 10narcisse.


volumes:
  .:
  postgres_data:
  libraryproject:
