# Generated by Django 4.2.1 on 2023-11-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Auteur", "verbose_name_plural": "Auteurs"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Livre", "verbose_name_plural": "Livres"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categorie", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="loan",
            options={"verbose_name": "Emprunt", "verbose_name_plural": "Emprunts"},
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=60, verbose_name="Prenom"),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="LibraryApp.author",
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=50, verbose_name="ISBN"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="book",
            name="total_exemplaires",
            field=models.IntegerField(
                default=1, verbose_name="Nombre total d'exemplaire"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(max_length=100, verbose_name="Etiquette"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="job",
            field=models.CharField(max_length=100, verbose_name="Profession"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=60, verbose_name="Prenom"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal",
            field=models.CharField(max_length=50, verbose_name="Adresse postale"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="LibraryApp.book",
                verbose_name="Livre",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="LibraryApp.customer",
                verbose_name="Client",
            ),
        ),
        migrations.AlterModelTable(name="author", table="Auteur",),
        migrations.AlterModelTable(name="book", table="Livre",),
        migrations.AlterModelTable(name="category", table="Categorie",),
        migrations.AlterModelTable(name="customer", table="Client",),
        migrations.AlterModelTable(name="loan", table="Emprunt",),
    ]
