# Generated by Django 4.2.1 on 2023-11-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author", old_name="last_name", new_name="username",
        ),
        migrations.RenameField(
            model_name="customer", old_name="last_name", new_name="username",
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="LibraryApp.category",
                verbose_name="Categorie",
            ),
        ),
    ]
