# Generated by Django 4.2.1 on 2023-11-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0004_book_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date d'enregistrement"
            ),
        ),
    ]
