# Generated by Django 4.2.1 on 2023-11-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0006_loan_loan_durarion_alter_loan_begin_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="author",),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="LibraryApp.author", verbose_name="Auteur"),
        ),
    ]
