# Generated by Django 4.2.1 on 2023-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0007_remove_book_author_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loan_durarion",
            field=models.IntegerField(default=3, verbose_name="Durée de prêt"),
        ),
    ]
