# Generated by Django 4.2.1 on 2023-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0009_remove_loan_loan_durarion"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="rendered",
            field=models.BooleanField(default=False, verbose_name="Rendu"),
        ),
    ]
