# Generated by Django 4.2.1 on 2023-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0010_loan_rendered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                db_table="Livre_Auteur", to="LibraryApp.author", verbose_name="Auteur"
            ),
        ),
    ]
