# Generated by Django 4.2.1 on 2023-11-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0012_book_creation_dates"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="creation_date",),
    ]
