# Generated by Django 4.2.1 on 2023-11-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0015_rename_creation_date_book_date_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="registration_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
